/**
 * Inverter + Battery section: Excel headers → internal keys (order matters for findColumnKey).
 * Headers are matched with normalizeHeader: lowercased, trimmed.
 */
export const COMBO_COLUMN_MAP_ORDERED = [
  { key: "srNo", aliases: ["sr.no", "sr no", "srno", "s.no", "serial no"] },
  { key: "comboId", aliases: ["combo id", "comboid", "combo sku id"] },
  { key: "brand", aliases: ["brand", "manufacturer", "make", "company", "company name", "brand name"] },
  { key: "inverterModel", aliases: ["inverter model number", "inverter model no", "inverter model", "inv model", "inverter name"] },
  { key: "batteryModel", aliases: ["battery model number", "battery model no", "battery model", "batt model", "battery name"] },
  {
    key: "inverterVA",
    aliases: [
      "inverter va",
      "inv va",
      "inverter (va)",
      "inverter capacity",
      "inv.va",
      "inv. va",
      "va rating",
      "rated va",
      "capacity (va)",
    ],
  },
  {
    key: "capacityAh",
    aliases: [
      "capacity ah",
      "capacity (ah)",
      "battery capacity ah",
      "tubular ah",
      "ah",
      "amp hour",
      "ampere hour",
    ],
  },
  { key: "batteryAH", aliases: ["battery ah", "battery (ah)", "batt ah", "battery a h", "batt ah capacity"] },
  { key: "batteryType", aliases: ["type", "battery type", "product type", "batt type", "cell type"] },
  { key: "warranty", aliases: ["warranty", "waranty"] },
  { key: "batteryWeight", aliases: ["battery weight", "batt weight", "battery wt"] },
  { key: "weight", aliases: ["weight", "wt", "net weight"] },
  { key: "scrapRate", aliases: ["scrap rate", "scrap"] },
  { key: "inverterPrice", aliases: ["inverter price", "inv price"] },
  { key: "batteryPrice", aliases: ["battery price", "batt price"] },
  {
    key: "finalPriceWithoutOldBattery",
    aliases: [
      "final price without old battery",
      "final without old battery",
      "price without old battery",
      "final price w/o old battery",
    ],
  },
  {
    key: "finalPriceWithOldBattery",
    aliases: [
      "final price with old battery",
      "final with old battery",
      "price with old battery",
      "final price w/ old battery",
    ],
  },
  {
    key: "newRateWithoutOB",
    aliases: ["new rate w/o b", "w/o b", "without ob", "without old", "w/o old"],
  },
  {
    key: "newRateWithOB",
    aliases: ["new rate with ob", "with ob", "with old", "rate with old"],
  },
  {
    key: "backupHours",
    aliases: [
      "backup hours",
      "backup hr",
      "backup time",
      "power backup",
      "hours backup",
      "hr backup",
      "autonomy",
      "backup",
    ],
  },
  { key: "suitableFor", aliases: ["suitable for", "best for", "suitable"] },
  { key: "comboCategory", aliases: ["combo category", "combo cat"] },
  { key: "quantity", aliases: ["quantity", "qty", "stock"] },
  { key: "amazonPrice", aliases: ["amazon price", "amazon"] },
  { key: "flipkartPrice", aliases: ["flipkart price", "flipkart"] },
  { key: "batteryBhaiPrice", aliases: ["batterybhai price", "battery bhai", "batterybhai"] },
  { key: "batteryBossPrice", aliases: ["batteryboss price", "battery boss", "batteryboss"] },
  {
    key: "pl",
    aliases: ["p&l", "p & l", "pnl", "profit & loss", "profit and loss", "profit/loss", "p/l"],
  },
  { key: "notes", aliases: ["notes", "note", "remarks", "remark"] },
  {
    key: "inverterImage",
    aliases: ["inverter image", "inverter image url", "inverter photo", "inv image", "inverter img"],
  },
  {
    key: "batteryImage",
    aliases: ["battery image", "battery image url", "battery photo", "batt image", "battery img"],
  },
  { key: "brandLogo", aliases: ["brand logo", "logo url", "company logo", "brand image"] },
  /** Legacy / shared (after combo-specific to avoid stealing “battery type”) */
  { key: "type", aliases: ["type", "combo type", "inverter+battery", "inverter battery"] },
  { key: "model", aliases: ["model number", "model no", "model", "sku"] },
  { key: "productCapacity", aliases: ["product capacity", "spec", "capacity spec"] },
  { key: "ah", aliases: ["ah capacity", "nom ah"] },
  { key: "dpPlusGst", aliases: ["dp + gst", "dp+gst", "dealer price"] },
  { key: "mrp", aliases: ["mrp"] },
  { key: "supplier", aliases: ["supplier", "vendor"] },
  { key: "invoiceNo", aliases: ["invoice", "invoice no"] },
  { key: "place", aliases: ["place", "city"] },
];

/** Table display (Inverter + Battery tab) — same order as your price sheet (1–24). */
export const COMBO_INVENTORY_TABLE_COLUMNS = [
  { key: "srNo", label: "SR.NO" },
  { key: "comboId", label: "Combo ID" },
  { key: "brand", label: "Brand" },
  { key: "inverterModel", label: "Inverter Model" },
  { key: "batteryModel", label: "Battery Model" },
  { key: "inverterVA", label: "Inverter VA", format: "num" },
  { key: "batteryAH", label: "Battery AH", format: "num" },
  { key: "batteryType", label: "Battery Type" },
  { key: "warranty", label: "Warranty" },
  { key: "batteryWeight", label: "Battery Weight", format: "num" },
  { key: "scrapRate", label: "Scrap Rate", format: "rupee" },
  { key: "inverterPrice", label: "Inverter Price", format: "rupee" },
  { key: "batteryPrice", label: "Battery Price", format: "rupee" },
  { key: "newRateWithoutOB", label: "Final Price Without Old Battery", format: "rupee" },
  { key: "newRateWithOB", label: "Final Price With Old Battery", format: "rupee" },
  { key: "backupHours", label: "Backup Hours", format: "num" },
  { key: "suitableFor", label: "Suitable For" },
  { key: "comboCategory", label: "Combo Category" },
  { key: "quantity", label: "Qty", format: "num" },
  { key: "notes", label: "Notes" },
];
